const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, 'frontend-infralink');

const dirsToCreate = [
    'public/assets/images'
];

const filesToCreate = [
    'public/favicon.ico',
    'public/logo.svg',
    'src/routes/index.jsx',
    'src/routes/ProtectedRoute.jsx',
    'src/routes/RoleRoute.jsx',
    'src/routes/client.routes.jsx',
    'src/routes/worker.routes.jsx',
    'src/routes/vendor.routes.jsx',
    'src/routes/admin.routes.jsx',
    'src/layouts/PublicLayout.jsx',
    'src/layouts/ClientLayout.jsx',
    'src/layouts/WorkerLayout.jsx',
    'src/layouts/VendorLayout.jsx',
    'src/layouts/AdminLayout.jsx',
    'src/layouts/components/Navbar.jsx',
    'src/layouts/components/Sidebar.jsx',
    'src/layouts/components/Footer.jsx',
    'src/layouts/components/MobileNav.jsx',
    'src/pages/public/Landing.jsx',
    'src/pages/public/About.jsx',
    'src/pages/public/Contact.jsx',
    'src/pages/public/NotFound.jsx',
    'src/pages/auth/Login.jsx',
    'src/pages/auth/Register.jsx',
    'src/pages/auth/ForgotPassword.jsx',
    'src/pages/auth/ResetPassword.jsx',
    'src/pages/auth/VerifyEmail.jsx',
    'src/pages/auth/RoleSelect.jsx',
    'src/pages/client/Dashboard.jsx',
    'src/pages/client/PostJob.jsx',
    'src/pages/client/MyJobs.jsx',
    'src/pages/client/JobDetail.jsx',
    'src/pages/client/Applications.jsx',
    'src/pages/client/Projects.jsx',
    'src/pages/client/ProjectDetail.jsx',
    'src/pages/client/WorkerSearch.jsx',
    'src/pages/client/WorkerProfile.jsx',
    'src/pages/client/HireWorker.jsx',
    'src/pages/client/Payments.jsx',
    'src/pages/client/PaymentDetail.jsx',
    'src/pages/client/Reviews.jsx',
    'src/pages/client/Notifications.jsx',
    'src/pages/client/Messages.jsx',
    'src/pages/client/Profile.jsx',
    'src/pages/worker/Dashboard.jsx',
    'src/pages/worker/BrowseJobs.jsx',
    'src/pages/worker/JobDetail.jsx',
    'src/pages/worker/MyApplications.jsx',
    'src/pages/worker/MyMatches.jsx',
    'src/pages/worker/ActiveProjects.jsx',
    'src/pages/worker/ProjectDetail.jsx',
    'src/pages/worker/Earnings.jsx',
    'src/pages/worker/Equipment.jsx',
    'src/pages/worker/Reviews.jsx',
    'src/pages/worker/Notifications.jsx',
    'src/pages/worker/Messages.jsx',
    'src/pages/worker/Profile.jsx',
    'src/pages/vendor/Dashboard.jsx',
    'src/pages/vendor/MyMaterials.jsx',
    'src/pages/vendor/AddMaterial.jsx',
    'src/pages/vendor/EditMaterial.jsx',
    'src/pages/vendor/Orders.jsx',
    'src/pages/vendor/OrderDetail.jsx',
    'src/pages/vendor/Payments.jsx',
    'src/pages/vendor/Notifications.jsx',
    'src/pages/vendor/Messages.jsx',
    'src/pages/vendor/Profile.jsx',
    'src/pages/admin/Dashboard.jsx',
    'src/pages/admin/Users.jsx',
    'src/pages/admin/UserDetail.jsx',
    'src/pages/admin/Jobs.jsx',
    'src/pages/admin/Projects.jsx',
    'src/pages/admin/Payments.jsx',
    'src/pages/admin/Disputes.jsx',
    'src/pages/admin/DisputeDetail.jsx',
    'src/pages/admin/Escalations.jsx',
    'src/pages/admin/Reviews.jsx',
    'src/pages/admin/Notifications.jsx',
    'src/pages/admin/Analytics.jsx',
    'src/pages/admin/Settings.jsx',
    'src/components/ui/Button.jsx',
    'src/components/ui/Input.jsx',
    'src/components/ui/Textarea.jsx',
    'src/components/ui/Select.jsx',
    'src/components/ui/Modal.jsx',
    'src/components/ui/Drawer.jsx',
    'src/components/ui/Dropdown.jsx',
    'src/components/ui/Badge.jsx',
    'src/components/ui/Avatar.jsx',
    'src/components/ui/Card.jsx',
    'src/components/ui/Table.jsx',
    'src/components/ui/Tabs.jsx',
    'src/components/ui/Toast.jsx',
    'src/components/ui/Tooltip.jsx',
    'src/components/ui/Spinner.jsx',
    'src/components/ui/Skeleton.jsx',
    'src/components/ui/Pagination.jsx',
    'src/components/ui/FileUpload.jsx',
    'src/components/ui/ImageUpload.jsx',
    'src/components/ui/StarRating.jsx',
    'src/components/ui/EmptyState.jsx',
    'src/components/shared/SearchBar.jsx',
    'src/components/shared/FilterPanel.jsx',
    'src/components/shared/NotificationBell.jsx',
    'src/components/shared/ChatWindow.jsx',
    'src/components/shared/MessageList.jsx',
    'src/components/shared/MessageBubble.jsx',
    'src/components/shared/MapView.jsx',
    'src/components/shared/ProfileCard.jsx',
    'src/components/shared/ReviewCard.jsx',
    'src/components/shared/PaymentCard.jsx',
    'src/components/shared/StatusBadge.jsx',
    'src/components/shared/ConfirmDialog.jsx',
    'src/components/jobs/JobCard.jsx',
    'src/components/jobs/JobForm.jsx',
    'src/components/jobs/JobFilters.jsx',
    'src/components/jobs/JobStatusBadge.jsx',
    'src/components/jobs/ApplicationCard.jsx',
    'src/components/workers/WorkerCard.jsx',
    'src/components/workers/WorkerProfileForm.jsx',
    'src/components/workers/SkillsInput.jsx',
    'src/components/workers/AvailabilityToggle.jsx',
    'src/components/workers/MatchScoreCard.jsx',
    'src/components/projects/ProjectCard.jsx',
    'src/components/projects/ProjectForm.jsx',
    'src/components/projects/ProjectTimeline.jsx',
    'src/components/projects/MilestoneTracker.jsx',
    'src/components/marketplace/MaterialCard.jsx',
    'src/components/marketplace/MaterialForm.jsx',
    'src/components/marketplace/MaterialFilters.jsx',
    'src/components/marketplace/CartSummary.jsx',
    'src/components/payments/PaymentForm.jsx',
    'src/components/payments/TransactionTable.jsx',
    'src/components/payments/EarningsChart.jsx',
    'src/components/ai/ChatbotWidget.jsx',
    'src/components/ai/ChatbotWindow.jsx',
    'src/components/ai/VoiceInput.jsx',
    'src/components/ai/VoiceOutput.jsx',
    'src/components/ai/VisionUpload.jsx',
    'src/components/ai/AssistantPanel.jsx',
    'src/components/admin/StatsCard.jsx',
    'src/components/admin/UserTable.jsx',
    'src/components/admin/EscalationCard.jsx',
    'src/components/admin/AnalyticsChart.jsx',
    'src/hooks/useAuth.js',
    'src/hooks/useSocket.js',
    'src/hooks/useNotifications.js',
    'src/hooks/useMessages.js',
    'src/hooks/useGeolocation.js',
    'src/hooks/useDebounce.js',
    'src/hooks/usePagination.js',
    'src/hooks/useFileUpload.js',
    'src/hooks/useVoice.js',
    'src/hooks/useInfiniteScroll.js',
    'src/store/index.js',
    'src/store/auth.store.js',
    'src/store/notification.store.js',
    'src/store/message.store.js',
    'src/store/job.store.js',
    'src/store/socket.store.js',
    'src/store/ui.store.js',
    'src/services/api.js',
    'src/services/auth.service.js',
    'src/services/user.service.js',
    'src/services/job.service.js',
    'src/services/worker.service.js',
    'src/services/project.service.js',
    'src/services/application.service.js',
    'src/services/matching.service.js',
    'src/services/message.service.js',
    'src/services/notification.service.js',
    'src/services/payment.service.js',
    'src/services/review.service.js',
    'src/services/equipment.service.js',
    'src/services/materials.service.js',
    'src/services/search.service.js',
    'src/services/ai.service.js',
    'src/utils/formatDate.js',
    'src/utils/formatCurrency.js',
    'src/utils/formatDistance.js',
    'src/utils/getInitials.js',
    'src/utils/validateForm.js',
    'src/utils/tokenStorage.js',
    'src/utils/roleRedirect.js',
    'src/utils/errorHandler.js',
    'src/constants/roles.js',
    'src/constants/jobStatus.js',
    'src/constants/matchStatus.js',
    'src/constants/paymentStatus.js',
    'src/constants/routes.js',
    'src/config/env.js',
    'src/config/socket.js',
    '.env',
    '.env.example',
    '.eslintrc.cjs',
    '.prettierrc'
];

dirsToCreate.forEach(dirName => {
    const fullPath = path.join(baseDir, dirName);
    if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
    }
});

filesToCreate.forEach(file => {
    const fullPath = path.join(baseDir, file);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    if (!fs.existsSync(fullPath)) {
        // Add simple component scaffolding for .jsx files
        if (file.endsWith('.jsx')) {
            const fileName = path.basename(file, '.jsx');
            fs.writeFileSync(fullPath, `export default function ${fileName}() {\n  return (\n    <div>${fileName}</div>\n  );\n}\n`);
        } else {
            fs.writeFileSync(fullPath, '');
        }
    }
});

console.log('Structure created successfully.');
