export const CONTRACTOR_TYPES = [
  'General Contractor (Full Project)',
  'Interior Contractor',
  'Civil Contractor',
  'Electrical Contractor',
  'Plumbing Contractor',
  'Carpentry Contractor',
  'Painting Contractor',
  'Flooring Contractor',
  'HVAC Contractor (AC/Ventilation)',
  'Fabrication / Welding Contractor',
  'Modular Kitchen Contractor',
  'False Ceiling Contractor',
  'Tiles & Marble Contractor',
  'Waterproofing Contractor',
  'Demolition Contractor',
  'RCC Contractor (Reinforced Concrete)',
  'Piling / Foundation Contractor',
  'Scaffolding Contractor',
  'Landscaping Contractor',
  'Road / Paving Contractor',
  'Excavation Contractor',
  'Fire Safety Contractor',
  'Security Systems Contractor (CCTV, Access Control)',
  'MEP Contractor (Mechanical, Electrical, Plumbing)',
  'Glass & Aluminum Contractor',
  'Curtain / Blinds Contractor',
  'Furniture Contractor (Custom Work)',
  'Home Automation Contractor',
  'Solar Installation Contractor',
  'Industrial Equipment Installation Contractor',
  'Lift / Elevator Contractor'
];

